DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS news;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS auth;

DROP INDEX IF EXISTS index_users_login;
DROP INDEX IF EXISTS index_auth_login;




